### PR TITLE
Include Isolation segments tests in CF Smoke tests

### PR DESCRIPTION
**Pull request by shashwathi**
Hi, 

In this PR, we are including routing isolation segment tests in smoke tests. 
Tracker story: https://www.pivotaltracker.com/story/show/144408627

Regards
CF Routing team
@belinda-liu && Shash

### CODE REVIEW

**Comment by shashwathi** [comment]
@jaresty  

We have updated this PR 
- To not create isolation segment resource
- Expect to run the test successfully with non admin user.

Regards
@jberkhahn & Shash

**Comment by anEXPer** [comment]
Thanks for making updates, @shashwathi, and for the PR.

In review of these changes and trying to land on a general set of strategies and guidelines for the smoke tests generally, I noticed that the existing test require that _either_ the user provided have admin permissions, _or_ the org and space to be used be specified and setup.

We'd like the smoke tests to be useful for people who are trying to validate the setup of a particular isolation segment, but also to test the feature as an errand for deployers. For now, we'd like to follow the established pattern, and allow setup in the API to be done by an Admin user if and only if no existing setup is to be used. This would be consistent and cover the use case of testing a particular segment, while also making setup easier in automated deployment sequences.

Sorry for the back and forth on this; looking over the changes, probably much of what you've just removed could be made conditional.

**Comment by shalako** [comment]
Before we proceed, we'd like to chat with @dsabeti about this tomorrow. We had a similar back and forth with our CATS PR and this is frustrating for the team. First we allowed for creation and clean-up of necessary resources, then based on feedback the team significantly refactored the PR to require all this to be created in advance. Now we're hearing the requirement is to satisfy both use cases. We would like to clearly understand the expectations for adding tests earlier in the dev cycle.

**Comment by shashwathi** [comment]
@dsabeti @anEXPer @shalako 

I have updated the PR with discussed changes. 

Regards
Shash

**Pull request merged**
