### PR TITLE
Increase the memory for the "binary" app from 16M to 30M

### PR DESCRIPTION
**Pull request by jimmykarily**
because when running the smoke tests with Eirini and a SLE stack, 16M is
not enough.

### What is this change about?

It's about making smoke tests pass with Eirini and SLE as a stack

### Please provide contextual information.

_Include any links to other PRs, stories, slack discussions, etc... that will help establish context._

### Please check all that apply for this PR:
- [ ] introduces a new test (see *Note below)
- [x] changes an existing test
- [ ] introduces a breaking change (other users will need to make manual changes when this change is released)

*Note: We want to keep cf-smoke-tests as lean as possible. The suite's purpose is to reveal fundamental problems with a foundation after initial or upgrade deployment. 
If your new test is executing anything more sophisticated than validating core functionality of Cloud Foundry, [CF Acceptance Tests](https://github.com/cloudfoundry/cf-acceptance-tests) (CATs) may be more suitable home for it (although CATs are designed to be run as part of a development pipeline and not against production environments).

### Did you update the README as appropriate for this change?
- [ ] YES
- [x] N/A

### How should this change be described in release notes?

"Increased memory for Ruby fixture app to let it pass in with non default stacks/buildpacks"

### What is the level of urgency for publishing this change?

- [ ] **Urgent** - unblocks current or future work
- [x] **Slightly Less than Urgent**

### CODE REVIEW

**Comment by jimmykarily** [comment]
Tests fail with: 

```
   2020-05-21T16:08:41.15+0000 [API/0] OUT App instance exited with guid b265d256-6273-4d8a-840e-0e26d063109b payload: {"instance"=>"smokes-11-app-3432347b929b688f-smoke-11--71477f3490-0", "index"=>0, "cell_id"=>"", "reason"=>"OOMKilled", "exit_status"=>137, "exit_description"=>"OOMKilled", "crash_count"=>0, "crash_timestamp"=>39, "version"=>"a34f2fa2-c77b-49a7-9908-14493692edd3"}
```

We get the same error when deploying the same fixture app manually with the same memory (16M). Increasing to 20M makes it pass but this PR increases to 30M to be sure we don't introduce any random flakiness by setting it very close to the limit.

**Comment by jimmykarily** [comment]
Maybe a better option would be to make it configurable through an environment variable and having 16M as the default.

**Comment by acosta11** [comment]
> Maybe a better option would be to make it configurable through an environment variable and having 16M as the default.

We considered making the value configurable, but decided to err on the side of minimizing the complexity of smoke tests configuration because we don't expect any further major deviation in memory use. In this case, the proposed difference in memory seems negligible and consequently remains within an acceptable threshold of optimization. Thanks for the PR!

Thanks,
Andrew

**Comment by jimmykarily** [comment]
Awesome, thanks!

**Pull request merged**
